// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFU9CjHU7t7VApEILFaNk1UyuPNgcIH8U',
    appId: '1:853559139148:web:7fe867a8926849eb6b0de9',
    messagingSenderId: '853559139148',
    projectId: 'eco-fitness-tracker',
    authDomain: 'eco-fitness-tracker.firebaseapp.com',
    storageBucket: 'eco-fitness-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBw-tbjfH89PVD2YPROvnkA5jTue7DB4',
    appId: '1:853559139148:android:560dcebbfad5e4e06b0de9',
    messagingSenderId: '853559139148',
    projectId: 'eco-fitness-tracker',
    storageBucket: 'eco-fitness-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJD9NCBNZymn66lgd-WeEtHWsCbk1yzY',
    appId: '1:853559139148:ios:0073436eff186c386b0de9',
    messagingSenderId: '853559139148',
    projectId: 'eco-fitness-tracker',
    storageBucket: 'eco-fitness-tracker.firebasestorage.app',
    iosBundleId: 'com.example.ecoFitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJD9NCBNZymn66lgd-WeEtHWsCbk1yzY',
    appId: '1:853559139148:ios:0073436eff186c386b0de9',
    messagingSenderId: '853559139148',
    projectId: 'eco-fitness-tracker',
    storageBucket: 'eco-fitness-tracker.firebasestorage.app',
    iosBundleId: 'com.example.ecoFitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFU9CjHU7t7VApEILFaNk1UyuPNgcIH8U',
    appId: '1:853559139148:web:2035a243e8a69a226b0de9',
    messagingSenderId: '853559139148',
    projectId: 'eco-fitness-tracker',
    authDomain: 'eco-fitness-tracker.firebaseapp.com',
    storageBucket: 'eco-fitness-tracker.firebasestorage.app',
  );
}
